# Sabores
ice_cream_flavors = [
    "Vainilla",
    "Chocolate",
    "Fresa",
    "Limón",
    "Menta",
    "Naranja",
    "Mango",
    "Coco",
    "Plátano",
    "Frambuesa",
    "Caramelo",
    "Café",
    "Almendra",
    "Avellana",
    "Pistacho",
    "Turrón",
    "Piña",
    "Melocotón",
    "Té verde",
    "Té chai",
    "Canela",
    "Jengibre",
    "Dulce de leche",
    "Manzana verde",
    "Kiwi",
    "Granada",
    "Arándano",
    "Melón",
    "Sandía",
    "Guayaba",
    "Maracuyá",
    "Papaya",
    "Cereza",
    "Uva",
    "Higo",
    "Ciruela",
    "Mamey",
    "Piñón",
    "Chocolate blanco",
    "Nutella",
    "Orejón",
    "Tutti Frutti",
    "Chicle",
    "Toronja",
    "Mandarina",
    "Tamarindo",
    "Pera",
    "Durazno",
    "Guanábana",
    "Pitahaya",
    "Frutos rojos",
    "Zanahoria",
    "Dulce de membrillo",
    "Crema catalana",
    "Yogur",
    "Arroz con leche",
    "Queso",
    "Crema de whisky",
    "Huevo",
    "Pudín de chocolate",
    "Malvavisco",
    "Jalea de frutas",
    "Tarta de queso",
    "Pastel de zanahoria",
    "Brownie",
    "Galleta",
    "Gofre",
    "Tiramisú",
    "Pastel de tres leches",
    "Flan",
    "Crema de cacahuate",
    "Maní",
    "Macadamia",
    "Cajeta",
    "Maíz",
    "Ciruela pasa",
    "Datil",
    "Uva pasa",
    "Miel",
    "Frutas tropicales",
    "Guava",
    "Zapote",
    "Toronja rosa",
    "Mandarina verde",
    "Nuez",
    "Amaranto",
    "Pitahaya roja",
    "Zapote negro",
    "Nanche",
    "Tuna",
    "Lichi",
    "Chabacano",
    "Cacao",
    "Jícama",
    "Pepino",
    "Mamey sapote",
    "Anona",
    "Ataulfo",
    "Granada china",
    "Guanábana criolla",
    "Guayaba agria",
    "Guayaba criolla",
    "Naranja agria",
    "Papaya maradol",
    "Ciruela china",
    "Ciruela dátil",
    "Pera de agua",
    "Pera manzana",
    "Pera perón",
    "Pera lechera",
    "Pera oriental",
    "Pera de verano",
    "Tuna blanca",
    "Tuna cardona",
    "Tuna de Castilla",
    "Tuna real",
    "Tuna trebolera",
    "Uva misionera",
    "Uva pelea",
    "Uva vinífera",
    "Uva zalema",
    "Uva zalema negra",
    "Uva zalema rosada",
    "Uva zalema roja",
    "Uva zalema rosa",
    "Naranja agria dulce",
    "Naranja china",
    "Naranja dulce",
    "Naranja toronja",
    "Naranja vinal",
    "Naranja x",
    "Tuna roja",
    "Tuna negra",
    "Tuna amarilla",
    "Tuna verde",
    "Tuna morada",
    "Tuna anaranjada",
    "Tuna amarilla",
    "Tuna azul",
    "Tuna violeta",
    "Tuna blanca",
    "Tuna rosa",
    "Tuna transparente",
    "Tuna opaca",
    "Tuna traslúcida",
    "Tuna opaca",
    "Tuna traslúcida",
    "Naranja roja",
    "Naranja rosada",
    "Naranja amarilla",
]

# Edulcorantes
sweeteners = [
    "Azúcar de caña",
    "Jarabe de maíz",
    "Miel",
    "Stevia",
    "Eritritol",
    "Xilitol",
    "Sucralosa",
    "Aspartamo",
    "Maltitol",
    "Sorbitol",
]

# Toppings y siropes
toppings_syrups = [
    "Chocolate fundido",
    "Sirope de caramelo",
    "Fresas frescas",
    "Trozos de galleta",
    "Maní triturado",
    "Nata montada",
    "Salsa de frambuesa",
    "Trozos de brownie",
    "Sirope de vainilla",
    "Trozos de chocolate",
    "Salsa de fresa",
    "Coco rallado",
    "Sirope de chocolate blanco",
    "Trozos de frutas tropicales",
    "Salsa de caramelo salado",
    "Galletas trituradas",
    "Sirope de menta",
    "Trozos de oreo",
    "Salsa de arándano",
    "Almendras picadas",
    "Sirope de avellana",
    "Trozos de tarta de queso",
    "Salsa de mango",
    "Granola",
    "Sirope de melocotón",
    "Trozos de plátano",
    "Salsa de mora",
    "Pepitas de chocolate",
    "Sirope de fresa silvestre",
    "Trozos de galleta de mantequilla",
]


# Bases
ice_cream_bases = [
    "Crema de leche",
    "Leche",
    "Yemas de huevo",
    "Yogur",
    "Fruta",
    "Leche de coco",
    "Leche de almendras",
    "Leche de soja",
    "Queso crema",
    "Leche condensada",
    "Ricotta",
    "Plátanos congelados",
]


initial_population = [['Uva vinífera',
  'Cacao',
  'Turrón',
  'Caramelo',
  'Ciruela dátil',
  'Ricotta',
  'Leche',
  'Crema de leche',
  'Eritritol',
  'Sirope de melocotón',
  'Trozos de chocolate',
  'Coco rallado'],
 ['Uva zalema rosa',
  'Miel',
  'Naranja rosada',
  'Naranja',
  'Brownie',
  'Leche de soja',
  'Fruta',
  'Leche de coco',
  'Sorbitol',
  'Maní triturado',
  'Salsa de caramelo salado',
  'Fresas frescas'],
 ['Naranja agria',
  'Naranja amarilla',
  'Ataulfo',
  'Orejón',
  'Pera manzana',
  'Yemas de huevo',
  'Fruta',
  'Plátanos congelados',
  'Maltitol',
  'Pepitas de chocolate',
  'Trozos de tarta de queso',
  'Chocolate fundido'],
 ['Guava',
  'Caramelo',
  'Naranja roja',
  'Amaranto',
  'Datil',
  'Queso crema',
  'Fruta',
  'Leche de soja',
  'Xilitol',
  'Salsa de arándano',
  'Sirope de melocotón',
  'Galletas trituradas'],
 ['Ataulfo',
  'Coco',
  'Menta',
  'Amaranto',
  'Brownie',
  'Fruta',
  'Yogur',
  'Ricotta',
  'Jarabe de maíz',
  'Maní triturado',
  'Trozos de galleta',
  'Sirope de melocotón'],
 ['Uva misionera',
  'Tuna morada',
  'Manzana verde',
  'Naranja agria',
  'Pera',
  'Ricotta',
  'Leche de almendras',
  'Queso crema',
  'Eritritol',
  'Salsa de caramelo salado',
  'Nata montada',
  'Trozos de frutas tropicales'],
 ['Kiwi',
  'Lichi',
  'Zapote',
  'Piña',
  'Queso',
  'Leche de soja',
  'Leche',
  'Crema de leche',
  'Eritritol',
  'Sirope de chocolate blanco',
  'Trozos de plátano',
  'Trozos de tarta de queso'],
 ['Crema catalana',
  'Café',
  'Nuez',
  'Piñón',
  'Pera manzana',
  'Leche condensada',
  'Fruta',
  'Leche de soja',
  'Maltitol',
  'Salsa de mango',
  'Almendras picadas',
  'Sirope de caramelo'],
 ['Gofre',
  'Tutti Frutti',
  'Manzana verde',
  'Tuna anaranjada',
  'Sandía',
  'Ricotta',
  'Leche condensada',
  'Plátanos congelados',
  'Xilitol',
  'Salsa de frambuesa',
  'Trozos de brownie',
  'Granola'],
 ['Pudín de chocolate',
  'Tuna violeta',
  'Nuez',
  'Caramelo',
  'Mandarina verde',
  'Leche de soja',
  'Leche',
  'Yogur',
  'Azúcar de caña',
  'Nata montada',
  'Sirope de chocolate blanco',
  'Sirope de avellana'],
 ['Tuna morada',
  'Fresa',
  'Crema de cacahuate',
  'Higo',
  'Uva zalema negra',
  'Fruta',
  'Leche condensada',
  'Leche de almendras',
  'Azúcar de caña',
  'Salsa de mora',
  'Nata montada',
  'Sirope de vainilla'],
 ['Jalea de frutas',
  'Durazno',
  'Granada china',
  'Tuna negra',
  'Dulce de leche',
  'Ricotta',
  'Fruta',
  'Leche de almendras',
  'Azúcar de caña',
  'Chocolate fundido',
  'Salsa de mora',
  'Nata montada'],
 ['Jengibre',
  'Naranja toronja',
  'Tuna verde',
  'Naranja amarilla',
  'Uva pelea',
  'Leche de coco',
  'Fruta',
  'Leche de almendras',
  'Sucralosa',
  'Coco rallado',
  'Sirope de vainilla',
  'Sirope de melocotón'],
 ['Zapote negro',
  'Café',
  'Gofre',
  'Tuna negra',
  'Ataulfo',
  'Leche condensada',
  'Leche de almendras',
  'Leche de coco',
  'Xilitol',
  'Maní triturado',
  'Galletas trituradas',
  'Trozos de tarta de queso'],
 ['Zapote',
  'Plátano',
  'Melón',
  'Piñón',
  'Tuna anaranjada',
  'Leche de almendras',
  'Crema de leche',
  'Leche de coco',
  'Jarabe de maíz',
  'Sirope de menta',
  'Trozos de plátano',
  'Maní triturado'],
 ['Mandarina',
  'Tuna de Castilla',
  'Canela',
  'Ciruela china',
  'Crema de cacahuate',
  'Ricotta',
  'Leche',
  'Leche de coco',
  'Aspartamo',
  'Granola',
  'Salsa de mango',
  'Sirope de avellana'],
 ['Lichi',
  'Tuna violeta',
  'Turrón',
  'Galleta',
  'Kiwi',
  'Crema de leche',
  'Fruta',
  'Leche de coco',
  'Aspartamo',
  'Almendras picadas',
  'Granola',
  'Salsa de mango'],
 ['Tuna real',
  'Frutas tropicales',
  'Menta',
  'Amaranto',
  'Tuna morada',
  'Ricotta',
  'Yogur',
  'Plátanos congelados',
  'Xilitol',
  'Granola',
  'Pepitas de chocolate',
  'Salsa de arándano'],
 ['Ciruela china',
  'Tuna amarilla',
  'Cajeta',
  'Pera lechera',
  'Yogur',
  'Leche de almendras',
  'Leche condensada',
  'Yemas de huevo',
  'Eritritol',
  'Sirope de chocolate blanco',
  'Nata montada',
  'Sirope de melocotón'],
 ['Crema catalana',
  'Guava',
  'Naranja vinal',
  'Tuna opaca',
  'Tuna roja',
  'Fruta',
  'Crema de leche',
  'Yogur',
  'Jarabe de maíz',
  'Salsa de arándano',
  'Sirope de avellana',
  'Coco rallado'],
 ['Uva vinífera',
  'Naranja dulce',
  'Melón',
  'Menta',
  'Tuna real',
  'Leche de coco',
  'Crema de leche',
  'Leche de soja',
  'Stevia',
  'Trozos de chocolate',
  'Sirope de melocotón',
  'Trozos de oreo'],
 ['Galleta',
  'Tuna',
  'Pera',
  'Dulce de leche',
  'Tuna real',
  'Leche',
  'Fruta',
  'Crema de leche',
  'Maltitol',
  'Trozos de galleta',
  'Salsa de mora',
  'Sirope de caramelo'],
 ['Ciruela dátil',
  'Toronja',
  'Tuna negra',
  'Uva zalema roja',
  'Tuna cardona',
  'Leche de coco',
  'Fruta',
  'Queso crema',
  'Azúcar de caña',
  'Salsa de arándano',
  'Salsa de caramelo salado',
  'Sirope de chocolate blanco'],
 ['Uva zalema',
  'Pera perón',
  'Zapote negro',
  'Naranja x',
  'Naranja rosada',
  'Yogur',
  'Ricotta',
  'Crema de leche',
  'Azúcar de caña',
  'Nata montada',
  'Coco rallado',
  'Trozos de brownie'],
 ['Uva pelea',
  'Ciruela pasa',
  'Naranja dulce',
  'Tamarindo',
  'Nutella',
  'Fruta',
  'Leche de almendras',
  'Leche',
  'Jarabe de maíz',
  'Trozos de brownie',
  'Trozos de tarta de queso',
  'Fresas frescas'],
 ['Turrón',
  'Guayaba',
  'Chocolate blanco',
  'Tuna traslúcida',
  'Naranja china',
  'Yogur',
  'Queso crema',
  'Yemas de huevo',
  'Azúcar de caña',
  'Salsa de fresa',
  'Salsa de frambuesa',
  'Fresas frescas'],
 ['Tuna trebolera',
  'Maracuyá',
  'Mamey',
  'Lichi',
  'Tuna azul',
  'Leche',
  'Leche de soja',
  'Plátanos congelados',
  'Aspartamo',
  'Sirope de vainilla',
  'Coco rallado',
  'Salsa de mora'],
 ['Gofre',
  'Tuna verde',
  'Naranja rosada',
  'Crema catalana',
  'Uva misionera',
  'Fruta',
  'Ricotta',
  'Leche de soja',
  'Stevia',
  'Nata montada',
  'Sirope de chocolate blanco',
  'Fresas frescas'],
 ['Guava',
  'Tuna azul',
  'Pera lechera',
  'Naranja',
  'Piñón',
  'Ricotta',
  'Leche de soja',
  'Leche de coco',
  'Sucralosa',
  'Salsa de fresa',
  'Sirope de avellana',
  'Trozos de frutas tropicales'],
 ['Avellana',
  'Pastel de zanahoria',
  'Uva pelea',
  'Frutos rojos',
  'Papaya',
  'Leche de coco',
  'Leche de soja',
  'Leche',
  'Jarabe de maíz',
  'Salsa de mango',
  'Salsa de mora',
  'Coco rallado'],
 ['Plátano',
  'Brownie',
  'Vainilla',
  'Naranja amarilla',
  'Crema de whisky',
  'Crema de leche',
  'Leche condensada',
  'Yogur',
  'Stevia',
  'Trozos de brownie',
  'Trozos de galleta de mantequilla',
  'Salsa de mango'],
 ['Toronja rosa',
  'Tuna cardona',
  'Mamey sapote',
  'Yogur',
  'Tuna morada',
  'Ricotta',
  'Leche de soja',
  'Leche condensada',
  'Azúcar de caña',
  'Coco rallado',
  'Sirope de menta',
  'Trozos de chocolate'],
 ['Sandía',
  'Lichi',
  'Pitahaya roja',
  'Naranja x',
  'Turrón',
  'Plátanos congelados',
  'Leche de almendras',
  'Leche condensada',
  'Sorbitol',
  'Sirope de vainilla',
  'Sirope de caramelo',
  'Salsa de mora'],
 ['Papaya maradol',
  'Macadamia',
  'Tuna amarilla',
  'Maíz',
  'Almendra',
  'Fruta',
  'Leche de almendras',
  'Leche de soja',
  'Jarabe de maíz',
  'Sirope de fresa silvestre',
  'Sirope de chocolate blanco',
  'Trozos de galleta de mantequilla'],
 ['Pepino',
  'Naranja vinal',
  'Ciruela',
  'Lichi',
  'Tamarindo',
  'Plátanos congelados',
  'Ricotta',
  'Yemas de huevo',
  'Sucralosa',
  'Trozos de frutas tropicales',
  'Sirope de fresa silvestre',
  'Trozos de brownie'],
 ['Guayaba criolla',
  'Tuna transparente',
  'Nanche',
  'Pera',
  'Guayaba',
  'Crema de leche',
  'Queso crema',
  'Leche',
  'Aspartamo',
  'Salsa de mora',
  'Chocolate fundido',
  'Salsa de fresa'],
 ['Chocolate',
  'Menta',
  'Pistacho',
  'Guayaba',
  'Naranja china',
  'Yemas de huevo',
  'Crema de leche',
  'Plátanos congelados',
  'Stevia',
  'Fresas frescas',
  'Trozos de chocolate',
  'Granola'],
 ['Manzana verde',
  'Mandarina',
  'Pastel de zanahoria',
  'Naranja agria',
  'Yogur',
  'Queso crema',
  'Leche',
  'Plátanos congelados',
  'Aspartamo',
  'Almendras picadas',
  'Maní triturado',
  'Sirope de chocolate blanco'],
 ['Canela',
  'Tuna verde',
  'Miel',
  'Mandarina',
  'Tamarindo',
  'Yogur',
  'Crema de leche',
  'Leche de soja',
  'Xilitol',
  'Trozos de oreo',
  'Galletas trituradas',
  'Sirope de menta'],
 ['Turrón',
  'Tamarindo',
  'Tuna morada',
  'Toronja',
  'Uva pasa',
  'Plátanos congelados',
  'Leche de almendras',
  'Yogur',
  'Maltitol',
  'Sirope de avellana',
  'Granola',
  'Trozos de tarta de queso'],
 ['Naranja x',
  'Miel',
  'Dulce de leche',
  'Naranja agria',
  'Maracuyá',
  'Ricotta',
  'Plátanos congelados',
  'Leche de almendras',
  'Xilitol',
  'Chocolate fundido',
  'Trozos de galleta',
  'Sirope de melocotón'],
 ['Chocolate',
  'Guayaba criolla',
  'Melón',
  'Tuna amarilla',
  'Limón',
  'Leche de soja',
  'Leche de coco',
  'Yogur',
  'Azúcar de caña',
  'Salsa de frambuesa',
  'Sirope de menta',
  'Trozos de chocolate'],
 ['Guayaba criolla',
  'Miel',
  'Ciruela china',
  'Pera de agua',
  'Ciruela',
  'Queso crema',
  'Plátanos congelados',
  'Leche condensada',
  'Azúcar de caña',
  'Trozos de chocolate',
  'Chocolate fundido',
  'Coco rallado'],
 ['Dulce de leche',
  'Pera perón',
  'Tuna amarilla',
  'Dulce de membrillo',
  'Uva pelea',
  'Leche',
  'Ricotta',
  'Leche de soja',
  'Aspartamo',
  'Trozos de frutas tropicales',
  'Granola',
  'Galletas trituradas'],
 ['Papaya maradol',
  'Mango',
  'Café',
  'Tuna amarilla',
  'Brownie',
  'Crema de leche',
  'Leche de coco',
  'Fruta',
  'Sorbitol',
  'Salsa de mora',
  'Sirope de menta',
  'Coco rallado'],
 ['Tuna azul',
  'Naranja dulce',
  'Pepino',
  'Granada',
  'Pera lechera',
  'Fruta',
  'Ricotta',
  'Leche condensada',
  'Sucralosa',
  'Chocolate fundido',
  'Sirope de avellana',
  'Sirope de menta'],
 ['Datil',
  'Pastel de tres leches',
  'Tarta de queso',
  'Miel',
  'Jícama',
  'Fruta',
  'Yogur',
  'Crema de leche',
  'Sucralosa',
  'Granola',
  'Sirope de caramelo',
  'Trozos de oreo'],
 ['Pitahaya roja',
  'Avellana',
  'Uva zalema roja',
  'Cereza',
  'Chocolate',
  'Yemas de huevo',
  'Fruta',
  'Plátanos congelados',
  'Maltitol',
  'Salsa de caramelo salado',
  'Trozos de galleta',
  'Nata montada'],
 ['Uva zalema negra',
  'Frutos rojos',
  'Limón',
  'Jengibre',
  'Coco',
  'Queso crema',
  'Ricotta',
  'Plátanos congelados',
  'Aspartamo',
  'Sirope de caramelo',
  'Salsa de caramelo salado',
  'Coco rallado'],
 ['Pera de agua',
  'Kiwi',
  'Pistacho',
  'Menta',
  'Chocolate',
  'Leche de soja',
  'Ricotta',
  'Queso crema',
  'Azúcar de caña',
  'Trozos de tarta de queso',
  'Sirope de avellana',
  'Salsa de mango'],
 ['Mango',
  'Pera perón',
  'Té verde',
  'Naranja dulce',
  'Anona',
  'Fruta',
  'Ricotta',
  'Yogur',
  'Eritritol',
  'Sirope de melocotón',
  'Trozos de chocolate',
  'Sirope de menta'],
 ['Pudín de chocolate',
  'Galleta',
  'Mango',
  'Uva zalema roja',
  'Naranja agria dulce',
  'Leche de soja',
  'Leche de almendras',
  'Yogur',
  'Azúcar de caña',
  'Trozos de galleta de mantequilla',
  'Sirope de melocotón',
  'Trozos de brownie'],
 ['Nuez',
  'Toronja',
  'Tuna traslúcida',
  'Pitahaya',
  'Nanche',
  'Leche de almendras',
  'Crema de leche',
  'Queso crema',
  'Miel',
  'Sirope de melocotón',
  'Trozos de galleta',
  'Trozos de frutas tropicales'],
 ['Guayaba',
  'Tamarindo',
  'Naranja amarilla',
  'Pitahaya',
  'Miel',
  'Queso crema',
  'Leche de almendras',
  'Ricotta',
  'Azúcar de caña',
  'Nata montada',
  'Trozos de tarta de queso',
  'Salsa de fresa'],
 ['Ciruela pasa',
  'Tuna real',
  'Uva zalema roja',
  'Toronja',
  'Naranja agria',
  'Leche condensada',
  'Leche de soja',
  'Yemas de huevo',
  'Sorbitol',
  'Maní triturado',
  'Sirope de menta',
  'Trozos de frutas tropicales'],
 ['Naranja china',
  'Arroz con leche',
  'Avellana',
  'Guayaba',
  'Tuna real',
  'Ricotta',
  'Leche de coco',
  'Yemas de huevo',
  'Miel',
  'Sirope de fresa silvestre',
  'Trozos de chocolate',
  'Salsa de mora'],
 ['Durazno',
  'Tamarindo',
  'Crema de cacahuate',
  'Pera de verano',
  'Tuna azul',
  'Ricotta',
  'Fruta',
  'Queso crema',
  'Sorbitol',
  'Pepitas de chocolate',
  'Sirope de melocotón',
  'Salsa de mango'],
 ['Crema de whisky',
  'Melocotón',
  'Ciruela dátil',
  'Papaya',
  'Tarta de queso',
  'Ricotta',
  'Yemas de huevo',
  'Plátanos congelados',
  'Sucralosa',
  'Sirope de melocotón',
  'Trozos de plátano',
  'Trozos de oreo'],
 ['Tuna real',
  'Macadamia',
  'Tuna negra',
  'Arroz con leche',
  'Brownie',
  'Queso crema',
  'Fruta',
  'Leche de soja',
  'Xilitol',
  'Chocolate fundido',
  'Almendras picadas',
  'Galletas trituradas'],
 ['Huevo',
  'Tuna cardona',
  'Tuna de Castilla',
  'Granada',
  'Caramelo',
  'Yemas de huevo',
  'Yogur',
  'Leche de almendras',
  'Eritritol',
  'Salsa de arándano',
  'Nata montada',
  'Chocolate fundido'],
 ['Nanche',
  'Crema de whisky',
  'Tuna roja',
  'Orejón',
  'Pera lechera',
  'Leche de coco',
  'Fruta',
  'Plátanos congelados',
  'Sucralosa',
  'Sirope de vainilla',
  'Trozos de chocolate',
  'Trozos de frutas tropicales'],
 ['Uva zalema',
  'Queso',
  'Maracuyá',
  'Arroz con leche',
  'Naranja agria dulce',
  'Leche',
  'Fruta',
  'Yemas de huevo',
  'Aspartamo',
  'Salsa de arándano',
  'Trozos de plátano',
  'Sirope de chocolate blanco'],
 ['Coco',
  'Canela',
  'Nuez',
  'Menta',
  'Melón',
  'Ricotta',
  'Crema de leche',
  'Leche de soja',
  'Xilitol',
  'Pepitas de chocolate',
  'Maní triturado',
  'Salsa de frambuesa'],
 ['Piñón',
  'Tuna real',
  'Tiramisú',
  'Datil',
  'Dulce de leche',
  'Queso crema',
  'Leche de coco',
  'Ricotta',
  'Maltitol',
  'Galletas trituradas',
  'Salsa de arándano',
  'Trozos de brownie'],
 ['Naranja agria dulce',
  'Plátano',
  'Piña',
  'Naranja vinal',
  'Ciruela pasa',
  'Plátanos congelados',
  'Queso crema',
  'Fruta',
  'Azúcar de caña',
  'Sirope de avellana',
  'Trozos de frutas tropicales',
  'Trozos de tarta de queso'],
 ['Maracuyá',
  'Higo',
  'Yogur',
  'Melón',
  'Tuna azul',
  'Leche de almendras',
  'Yemas de huevo',
  'Fruta',
  'Sucralosa',
  'Pepitas de chocolate',
  'Salsa de caramelo salado',
  'Trozos de chocolate'],
 ['Frambuesa',
  'Fresa',
  'Maracuyá',
  'Naranja china',
  'Naranja toronja',
  'Leche',
  'Yogur',
  'Ricotta',
  'Azúcar de caña',
  'Trozos de oreo',
  'Granola',
  'Trozos de chocolate'],
 ['Nutella',
  'Zapote negro',
  'Tuna real',
  'Naranja china',
  'Tuna',
  'Yogur',
  'Fruta',
  'Plátanos congelados',
  'Jarabe de maíz',
  'Pepitas de chocolate',
  'Galletas trituradas',
  'Trozos de oreo'],
 ['Chocolate',
  'Café',
  'Datil',
  'Granada',
  'Uva pelea',
  'Leche de almendras',
  'Leche de soja',
  'Leche condensada',
  'Miel',
  'Trozos de chocolate',
  'Salsa de fresa',
  'Trozos de galleta de mantequilla'],
 ['Turrón',
  'Naranja agria dulce',
  'Queso',
  'Maíz',
  'Tuna rosa',
  'Ricotta',
  'Plátanos congelados',
  'Leche de coco',
  'Jarabe de maíz',
  'Trozos de tarta de queso',
  'Sirope de caramelo',
  'Chocolate fundido'],
 ['Jengibre',
  'Pera lechera',
  'Avellana',
  'Tuna azul',
  'Ataulfo',
  'Crema de leche',
  'Yemas de huevo',
  'Plátanos congelados',
  'Stevia',
  'Pepitas de chocolate',
  'Almendras picadas',
  'Trozos de chocolate'],
 ['Menta',
  'Naranja',
  'Tuna',
  'Frutos rojos',
  'Tuna roja',
  'Leche de coco',
  'Yogur',
  'Ricotta',
  'Azúcar de caña',
  'Sirope de melocotón',
  'Almendras picadas',
  'Trozos de frutas tropicales'],
 ['Manzana verde',
  'Pitahaya',
  'Tuna roja',
  'Tuna traslúcida',
  'Coco',
  'Leche de almendras',
  'Leche de coco',
  'Yogur',
  'Sorbitol',
  'Trozos de plátano',
  'Chocolate fundido',
  'Galletas trituradas'],
 ['Uva zalema roja',
  'Mango',
  'Pera lechera',
  'Tuna roja',
  'Tutti Frutti',
  'Yemas de huevo',
  'Leche condensada',
  'Leche',
  'Azúcar de caña',
  'Fresas frescas',
  'Trozos de plátano',
  'Salsa de mango'],
 ['Higo',
  'Jícama',
  'Maní',
  'Guayaba agria',
  'Pera de agua',
  'Ricotta',
  'Leche de soja',
  'Leche condensada',
  'Azúcar de caña',
  'Trozos de chocolate',
  'Granola',
  'Trozos de galleta'],
 ['Naranja agria',
  'Frutos rojos',
  'Tuna anaranjada',
  'Papaya',
  'Mango',
  'Yemas de huevo',
  'Crema de leche',
  'Leche de coco',
  'Aspartamo',
  'Trozos de galleta',
  'Trozos de brownie',
  'Salsa de fresa'],
 ['Macadamia',
  'Café',
  'Chocolate blanco',
  'Guayaba',
  'Tuna amarilla',
  'Leche',
  'Yemas de huevo',
  'Plátanos congelados',
  'Azúcar de caña',
  'Maní triturado',
  'Trozos de oreo',
  'Salsa de mango'],
 ['Mango',
  'Tiramisú',
  'Zapote',
  'Nanche',
  'Té verde',
  'Leche de almendras',
  'Crema de leche',
  'Leche',
  'Eritritol',
  'Galletas trituradas',
  'Trozos de frutas tropicales',
  'Trozos de plátano'],
 ['Crema de cacahuate',
  'Macadamia',
  'Durazno',
  'Pera de agua',
  'Frambuesa',
  'Yogur',
  'Ricotta',
  'Fruta',
  'Maltitol',
  'Salsa de mango',
  'Sirope de vainilla',
  'Coco rallado'],
 ['Macadamia',
  'Anona',
  'Uva misionera',
  'Tuna rosa',
  'Chicle',
  'Yogur',
  'Ricotta',
  'Queso crema',
  'Aspartamo',
  'Sirope de melocotón',
  'Chocolate fundido',
  'Salsa de arándano'],
 ['Naranja roja',
  'Maní',
  'Chocolate',
  'Turrón',
  'Frutos rojos',
  'Fruta',
  'Leche',
  'Queso crema',
  'Sorbitol',
  'Trozos de galleta de mantequilla',
  'Chocolate fundido',
  'Coco rallado'],
 ['Papaya maradol',
  'Kiwi',
  'Mandarina',
  'Pera manzana',
  'Melocotón',
  'Leche de almendras',
  'Crema de leche',
  'Yogur',
  'Xilitol',
  'Sirope de caramelo',
  'Pepitas de chocolate',
  'Trozos de oreo'],
 ['Guava',
  'Mandarina',
  'Frambuesa',
  'Naranja',
  'Naranja vinal',
  'Leche de coco',
  'Ricotta',
  'Queso crema',
  'Sorbitol',
  'Trozos de chocolate',
  'Salsa de frambuesa',
  'Maní triturado'],
 ['Pera lechera',
  'Uva zalema negra',
  'Limón',
  'Pudín de chocolate',
  'Datil',
  'Leche de soja',
  'Leche condensada',
  'Leche de coco',
  'Sucralosa',
  'Almendras picadas',
  'Salsa de fresa',
  'Salsa de mora'],
 ['Nuez',
  'Jengibre',
  'Tuna amarilla',
  'Naranja toronja',
  'Uva pasa',
  'Plátanos congelados',
  'Leche de coco',
  'Crema de leche',
  'Jarabe de maíz',
  'Granola',
  'Trozos de frutas tropicales',
  'Fresas frescas'],
 ['Tuna morada',
  'Melón',
  'Queso',
  'Naranja vinal',
  'Toronja rosa',
  'Leche de almendras',
  'Fruta',
  'Leche de soja',
  'Sucralosa',
  'Salsa de mora',
  'Trozos de galleta',
  'Salsa de fresa'],
 ['Uva pasa',
  'Guayaba',
  'Mamey sapote',
  'Sandía',
  'Guayaba criolla',
  'Fruta',
  'Leche de almendras',
  'Leche de coco',
  'Sucralosa',
  'Coco rallado',
  'Trozos de plátano',
  'Trozos de oreo'],
 ['Tuna verde',
  'Toronja',
  'Ciruela pasa',
  'Uva pasa',
  'Malvavisco',
  'Fruta',
  'Leche',
  'Ricotta',
  'Xilitol',
  'Salsa de caramelo salado',
  'Sirope de menta',
  'Sirope de avellana'],
 ['Uva',
  'Amaranto',
  'Naranja rosada',
  'Tuna anaranjada',
  'Café',
  'Leche de almendras',
  'Ricotta',
  'Crema de leche',
  'Miel',
  'Trozos de frutas tropicales',
  'Sirope de chocolate blanco',
  'Trozos de chocolate'],
 ['Tuna cardona',
  'Tuna negra',
  'Tuna morada',
  'Galleta',
  'Chabacano',
  'Leche de coco',
  'Plátanos congelados',
  'Leche',
  'Miel',
  'Trozos de brownie',
  'Pepitas de chocolate',
  'Coco rallado'],
 ['Tutti Frutti',
  'Café',
  'Naranja rosada',
  'Tuna anaranjada',
  'Naranja roja',
  'Fruta',
  'Leche',
  'Leche condensada',
  'Eritritol',
  'Sirope de vainilla',
  'Nata montada',
  'Trozos de oreo'],
 ['Gofre',
  'Tuna negra',
  'Tuna azul',
  'Uva misionera',
  'Mandarina verde',
  'Leche de coco',
  'Yemas de huevo',
  'Crema de leche',
  'Stevia',
  'Sirope de vainilla',
  'Fresas frescas',
  'Salsa de arándano'],
 ['Limón',
  'Mandarina verde',
  'Pitahaya roja',
  'Guayaba',
  'Café',
  'Queso crema',
  'Yemas de huevo',
  'Crema de leche',
  'Maltitol',
  'Nata montada',
  'Sirope de chocolate blanco',
  'Sirope de caramelo'],
 ['Uva zalema',
  'Limón',
  'Pera manzana',
  'Té verde',
  'Pera de agua',
  'Leche condensada',
  'Queso crema',
  'Ricotta',
  'Miel',
  'Sirope de caramelo',
  'Sirope de fresa silvestre',
  'Salsa de arándano'],
 ['Fresa',
  'Pistacho',
  'Naranja rosada',
  'Pera oriental',
  'Uva pasa',
  'Fruta',
  'Leche de almendras',
  'Plátanos congelados',
  'Azúcar de caña',
  'Sirope de fresa silvestre',
  'Pepitas de chocolate',
  'Trozos de chocolate'],
 ['Zapote negro',
  'Tuna morada',
  'Tuna blanca',
  'Tuna negra',
  'Naranja agria',
  'Queso crema',
  'Yogur',
  'Ricotta',
  'Miel',
  'Fresas frescas',
  'Almendras picadas',
  'Salsa de mora'],
 ['Granada china',
  'Naranja x',
  'Nuez',
  'Melón',
  'Higo',
  'Queso crema',
  'Crema de leche',
  'Ricotta',
  'Miel',
  'Trozos de oreo',
  'Trozos de brownie',
  'Pepitas de chocolate'],
 ['Plátano',
  'Queso',
  'Malvavisco',
  'Tuna trebolera',
  'Mamey',
  'Ricotta',
  'Queso crema',
  'Leche condensada',
  'Azúcar de caña',
  'Coco rallado',
  'Almendras picadas',
  'Salsa de frambuesa'],
 ['Tuna transparente',
  'Maracuyá',
  'Cacao',
  'Pastel de tres leches',
  'Granada',
  'Yogur',
  'Fruta',
  'Leche condensada',
  'Sorbitol',
  'Salsa de mango',
  'Chocolate fundido',
  'Granola'],
 ['Uva zalema rosada',
  'Gofre',
  'Ciruela china',
  'Queso',
  'Chicle',
  'Crema de leche',
  'Queso crema',
  'Ricotta',
  'Azúcar de caña',
  'Salsa de arándano',
  'Salsa de mango',
  'Trozos de galleta'],
 ['Ciruela',
  'Uva',
  'Flan',
  'Uva zalema rosa',
  'Naranja agria',
  'Yemas de huevo',
  'Crema de leche',
  'Leche condensada',
  'Eritritol',
  'Pepitas de chocolate',
  'Chocolate fundido',
  'Sirope de caramelo'],
 ['Vainilla',
  'Pitahaya roja',
  'Guanábana',
  'Flan',
  'Crema de whisky',
  'Yemas de huevo',
  'Yogur',
  'Queso crema',
  'Eritritol',
  'Granola',
  'Fresas frescas',
  'Chocolate fundido'],
 ['Ciruela pasa',
  'Brownie',
  'Naranja vinal',
  'Tuna anaranjada',
  'Avellana',
  'Crema de leche',
  'Ricotta',
  'Yogur',
  'Stevia',
  'Trozos de tarta de queso',
  'Salsa de mango',
  'Sirope de caramelo'],
 ['Té chai',
  'Cajeta',
  'Tuna real',
  'Tuna anaranjada',
  'Pera lechera',
  'Yogur',
  'Ricotta',
  'Leche condensada',
  'Jarabe de maíz',
  'Coco rallado',
  'Salsa de caramelo salado',
  'Salsa de mora'],
 ['Zapote negro',
  'Nanche',
  'Frambuesa',
  'Dulce de membrillo',
  'Uva zalema rosada',
  'Queso crema',
  'Leche de soja',
  'Leche',
  'Maltitol',
  'Pepitas de chocolate',
  'Salsa de arándano',
  'Trozos de galleta de mantequilla'],
 ['Mandarina verde',
  'Dulce de leche',
  'Tuna morada',
  'Jalea de frutas',
  'Tuna verde',
  'Queso crema',
  'Plátanos congelados',
  'Crema de leche',
  'Aspartamo',
  'Granola',
  'Trozos de plátano',
  'Salsa de mora'],
 ['Avellana',
  'Granada china',
  'Mamey',
  'Queso',
  'Tuna trebolera',
  'Plátanos congelados',
  'Leche de almendras',
  'Queso crema',
  'Xilitol',
  'Trozos de plátano',
  'Salsa de mango',
  'Salsa de arándano'],
 ['Tuna morada',
  'Macadamia',
  'Melón',
  'Pistacho',
  'Café',
  'Yogur',
  'Leche de coco',
  'Leche condensada',
  'Sorbitol',
  'Trozos de oreo',
  'Sirope de caramelo',
  'Sirope de fresa silvestre'],
 ['Tuna opaca',
  'Tuna morada',
  'Pera de verano',
  'Datil',
  'Dulce de membrillo',
  'Plátanos congelados',
  'Leche de soja',
  'Leche de coco',
  'Azúcar de caña',
  'Salsa de frambuesa',
  'Galletas trituradas',
  'Nata montada'],
 ['Pepino',
  'Piña',
  'Pastel de zanahoria',
  'Kiwi',
  'Pera de verano',
  'Leche de soja',
  'Crema de leche',
  'Leche condensada',
  'Aspartamo',
  'Galletas trituradas',
  'Fresas frescas',
  'Trozos de tarta de queso'],
 ['Tuna roja',
  'Pera perón',
  'Naranja',
  'Uva zalema',
  'Uva zalema rosada',
  'Plátanos congelados',
  'Yemas de huevo',
  'Leche de soja',
  'Miel',
  'Sirope de melocotón',
  'Trozos de chocolate',
  'Salsa de mora'],
 ['Tutti Frutti',
  'Maní',
  'Tiramisú',
  'Toronja',
  'Nanche',
  'Plátanos congelados',
  'Leche de soja',
  'Ricotta',
  'Miel',
  'Chocolate fundido',
  'Sirope de menta',
  'Fresas frescas'],
 ['Ciruela china',
  'Arroz con leche',
  'Anona',
  'Uva zalema rosa',
  'Nuez',
  'Plátanos congelados',
  'Yogur',
  'Leche',
  'Stevia',
  'Sirope de fresa silvestre',
  'Sirope de avellana',
  'Fresas frescas'],
 ['Naranja agria dulce',
  'Tuna transparente',
  'Tuna morada',
  'Datil',
  'Tuna traslúcida',
  'Leche de almendras',
  'Leche',
  'Yogur',
  'Stevia',
  'Sirope de chocolate blanco',
  'Sirope de menta',
  'Trozos de plátano'],
 ['Pera lechera',
  'Mandarina verde',
  'Sandía',
  'Tuna blanca',
  'Pistacho',
  'Yemas de huevo',
  'Leche de coco',
  'Ricotta',
  'Stevia',
  'Salsa de mora',
  'Salsa de caramelo salado',
  'Sirope de fresa silvestre'],
 ['Tuna cardona',
  'Naranja rosada',
  'Gofre',
  'Tamarindo',
  'Toronja',
  'Crema de leche',
  'Queso crema',
  'Leche de soja',
  'Miel',
  'Trozos de frutas tropicales',
  'Pepitas de chocolate',
  'Sirope de caramelo'],
 ['Tuna anaranjada',
  'Mamey',
  'Pera lechera',
  'Lichi',
  'Macadamia',
  'Plátanos congelados',
  'Leche',
  'Leche de coco',
  'Azúcar de caña',
  'Salsa de frambuesa',
  'Sirope de menta',
  'Trozos de plátano'],
 ['Naranja',
  'Arándano',
  'Macadamia',
  'Vainilla',
  'Brownie',
  'Yogur',
  'Leche de almendras',
  'Crema de leche',
  'Jarabe de maíz',
  'Trozos de brownie',
  'Sirope de vainilla',
  'Salsa de caramelo salado'],
 ['Chabacano',
  'Crema catalana',
  'Granada',
  'Melón',
  'Pera oriental',
  'Fruta',
  'Leche condensada',
  'Leche',
  'Xilitol',
  'Trozos de brownie',
  'Sirope de avellana',
  'Sirope de menta'],
 ['Almendra',
  'Melocotón',
  'Tuna roja',
  'Arándano',
  'Cacao',
  'Leche condensada',
  'Leche de coco',
  'Crema de leche',
  'Aspartamo',
  'Sirope de melocotón',
  'Trozos de oreo',
  'Trozos de galleta de mantequilla'],
 ['Pudín de chocolate',
  'Pitahaya roja',
  'Melón',
  'Nanche',
  'Tuna de Castilla',
  'Plátanos congelados',
  'Yogur',
  'Leche de almendras',
  'Aspartamo',
  'Trozos de plátano',
  'Galletas trituradas',
  'Maní triturado'],
 ['Coco',
  'Kiwi',
  'Guayaba agria',
  'Guanábana criolla',
  'Naranja agria dulce',
  'Crema de leche',
  'Fruta',
  'Leche condensada',
  'Sucralosa',
  'Pepitas de chocolate',
  'Maní triturado',
  'Nata montada'],
 ['Macadamia',
  'Sandía',
  'Jengibre',
  'Mamey sapote',
  'Tuna amarilla',
  'Crema de leche',
  'Queso crema',
  'Leche de soja',
  'Miel',
  'Salsa de mora',
  'Sirope de vainilla',
  'Galletas trituradas'],
 ['Uva zalema rosada',
  'Naranja agria',
  'Miel',
  'Manzana verde',
  'Zanahoria',
  'Plátanos congelados',
  'Yogur',
  'Leche de coco',
  'Maltitol',
  'Salsa de frambuesa',
  'Sirope de fresa silvestre',
  'Trozos de oreo'],
 ['Tuna transparente',
  'Maracuyá',
  'Té chai',
  'Frutos rojos',
  'Orejón',
  'Leche',
  'Queso crema',
  'Leche de soja',
  'Maltitol',
  'Salsa de frambuesa',
  'Sirope de chocolate blanco',
  'Sirope de fresa silvestre'],
 ['Tuna trebolera',
  'Pera',
  'Pera de verano',
  'Macadamia',
  'Naranja agria dulce',
  'Crema de leche',
  'Queso crema',
  'Ricotta',
  'Xilitol',
  'Trozos de brownie',
  'Salsa de caramelo salado',
  'Pepitas de chocolate'],
 ['Jalea de frutas',
  'Turrón',
  'Tuna opaca',
  'Maracuyá',
  'Chocolate',
  'Crema de leche',
  'Leche',
  'Yemas de huevo',
  'Stevia',
  'Sirope de menta',
  'Trozos de chocolate',
  'Salsa de frambuesa'],
 ['Pera lechera',
  'Manzana verde',
  'Pitahaya roja',
  'Pera de verano',
  'Tutti Frutti',
  'Ricotta',
  'Leche de coco',
  'Plátanos congelados',
  'Aspartamo',
  'Sirope de caramelo',
  'Salsa de mango',
  'Trozos de frutas tropicales'],
 ['Plátano',
  'Almendra',
  'Tuna negra',
  'Naranja roja',
  'Tutti Frutti',
  'Queso crema',
  'Ricotta',
  'Fruta',
  'Xilitol',
  'Trozos de plátano',
  'Trozos de galleta',
  'Maní triturado'],
 ['Pistacho',
  'Maní',
  'Pera',
  'Melón',
  'Datil',
  'Plátanos congelados',
  'Yemas de huevo',
  'Fruta',
  'Maltitol',
  'Salsa de caramelo salado',
  'Trozos de chocolate',
  'Trozos de galleta de mantequilla'],
 ['Uva',
  'Naranja toronja',
  'Anona',
  'Frambuesa',
  'Zanahoria',
  'Plátanos congelados',
  'Ricotta',
  'Yogur',
  'Eritritol',
  'Trozos de plátano',
  'Sirope de fresa silvestre',
  'Salsa de frambuesa'],
 ['Jalea de frutas',
  'Granada',
  'Uva zalema roja',
  'Tuna roja',
  'Chabacano',
  'Queso crema',
  'Crema de leche',
  'Plátanos congelados',
  'Eritritol',
  'Salsa de fresa',
  'Trozos de galleta de mantequilla',
  'Salsa de arándano'],
 ['Tuna',
  'Huevo',
  'Brownie',
  'Pepino',
  'Gofre',
  'Leche de soja',
  'Plátanos congelados',
  'Leche de almendras',
  'Azúcar de caña',
  'Salsa de frambuesa',
  'Nata montada',
  'Sirope de caramelo'],
 ['Naranja x',
  'Caramelo',
  'Chocolate',
  'Naranja toronja',
  'Queso',
  'Fruta',
  'Leche de coco',
  'Plátanos congelados',
  'Xilitol',
  'Sirope de caramelo',
  'Granola',
  'Trozos de brownie'],
 ['Té chai',
  'Manzana verde',
  'Galleta',
  'Higo',
  'Naranja roja',
  'Plátanos congelados',
  'Crema de leche',
  'Yogur',
  'Maltitol',
  'Trozos de tarta de queso',
  'Trozos de chocolate',
  'Salsa de mora'],
 ['Ciruela pasa',
  'Cacao',
  'Arándano',
  'Melocotón',
  'Vainilla',
  'Leche de almendras',
  'Leche de coco',
  'Yogur',
  'Jarabe de maíz',
  'Sirope de caramelo',
  'Coco rallado',
  'Salsa de mora'],
 ['Tuna traslúcida',
  'Limón',
  'Durazno',
  'Chicle',
  'Datil',
  'Leche de soja',
  'Queso crema',
  'Fruta',
  'Sucralosa',
  'Sirope de vainilla',
  'Salsa de mango',
  'Pepitas de chocolate'],
 ['Pudín de chocolate',
  'Tuna transparente',
  'Sandía',
  'Crema catalana',
  'Naranja amarilla',
  'Fruta',
  'Yemas de huevo',
  'Leche de almendras',
  'Maltitol',
  'Salsa de fresa',
  'Chocolate fundido',
  'Trozos de galleta'],
 ['Tuna real',
  'Miel',
  'Café',
  'Manzana verde',
  'Naranja x',
  'Leche de almendras',
  'Queso crema',
  'Ricotta',
  'Sorbitol',
  'Coco rallado',
  'Trozos de galleta de mantequilla',
  'Trozos de tarta de queso'],
 ['Arándano',
  'Uva',
  'Tuna real',
  'Ciruela dátil',
  'Pastel de zanahoria',
  'Queso crema',
  'Ricotta',
  'Fruta',
  'Eritritol',
  'Sirope de menta',
  'Salsa de fresa',
  'Salsa de mora'],
 ['Tuna traslúcida',
  'Guayaba agria',
  'Melocotón',
  'Crema de whisky',
  'Naranja roja',
  'Leche',
  'Leche condensada',
  'Leche de soja',
  'Maltitol',
  'Galletas trituradas',
  'Trozos de galleta de mantequilla',
  'Salsa de arándano'],
 ['Pera perón',
  'Menta',
  'Tuna azul',
  'Queso',
  'Naranja dulce',
  'Leche condensada',
  'Leche de soja',
  'Fruta',
  'Sucralosa',
  'Granola',
  'Trozos de oreo',
  'Salsa de frambuesa'],
 ['Mamey sapote',
  'Tutti Frutti',
  'Cereza',
  'Naranja amarilla',
  'Sandía',
  'Plátanos congelados',
  'Yemas de huevo',
  'Crema de leche',
  'Stevia',
  'Granola',
  'Trozos de tarta de queso',
  'Sirope de chocolate blanco'],
 ['Cereza',
  'Pera perón',
  'Tuna violeta',
  'Cajeta',
  'Amaranto',
  'Leche',
  'Yemas de huevo',
  'Leche de coco',
  'Azúcar de caña',
  'Almendras picadas',
  'Trozos de brownie',
  'Salsa de fresa'],
 ['Tutti Frutti',
  'Manzana verde',
  'Mandarina verde',
  'Naranja',
  'Nuez',
  'Leche de almendras',
  'Leche de coco',
  'Ricotta',
  'Maltitol',
  'Trozos de brownie',
  'Trozos de oreo',
  'Sirope de melocotón'],
 ['Caramelo',
  'Ciruela pasa',
  'Yogur',
  'Tuna',
  'Melón',
  'Leche de coco',
  'Yogur',
  'Leche de almendras',
  'Jarabe de maíz',
  'Pepitas de chocolate',
  'Maní triturado',
  'Salsa de mora'],
 ['Sandía',
  'Uva misionera',
  'Pera de agua',
  'Malvavisco',
  'Higo',
  'Fruta',
  'Queso crema',
  'Plátanos congelados',
  'Xilitol',
  'Salsa de mango',
  'Salsa de fresa',
  'Salsa de frambuesa'],
 ['Crema de whisky',
  'Fresa',
  'Jícama',
  'Naranja roja',
  'Naranja amarilla',
  'Leche de coco',
  'Crema de leche',
  'Ricotta',
  'Stevia',
  'Salsa de mango',
  'Salsa de mora',
  'Sirope de melocotón'],
 ['Anona',
  'Lichi',
  'Toronja',
  'Zapote',
  'Chocolate blanco',
  'Fruta',
  'Yogur',
  'Crema de leche',
  'Maltitol',
  'Nata montada',
  'Salsa de caramelo salado',
  'Trozos de chocolate'],
 ['Pera lechera',
  'Pepino',
  'Brownie',
  'Té chai',
  'Uva zalema rosa',
  'Queso crema',
  'Leche de almendras',
  'Leche condensada',
  'Xilitol',
  'Salsa de fresa',
  'Trozos de chocolate',
  'Trozos de galleta de mantequilla']]
  
  
ingredients_fitness = {'ice_cream_flavors': 
{'Vainilla': {'Flavor': 3.94,'Texture': 5.57,'Novelty': 9.94},
  'Chocolate': {'Flavor': 6.36, 'Texture': 8.1, 'Novelty': 0.53},
  'Fresa': {'Flavor': 6.49, 'Texture': 1.75, 'Novelty': 0.47},
  'Limón': {'Flavor': 3.09, 'Texture': 6.89, 'Novelty': 8.0},
  'Menta': {'Flavor': 9.78, 'Texture': 4.53, 'Novelty': 6.59},
  'Naranja': {'Flavor': 8.11, 'Texture': 8.42, 'Novelty': 3.55},
  'Mango': {'Flavor': 4.48, 'Texture': 2.92, 'Novelty': 0.97},
  'Coco': {'Flavor': 7.78, 'Texture': 4.07, 'Novelty': 4.69},
  'Plátano': {'Flavor': 8.51, 'Texture': 7.2, 'Novelty': 4.0},
  'Frambuesa': {'Flavor': 5.65, 'Texture': 3.51, 'Novelty': 3.93},
  'Caramelo': {'Flavor': 1.1, 'Texture': 6.16, 'Novelty': 8.14},
  'Café': {'Flavor': 2.28, 'Texture': 1.28, 'Novelty': 5.46},
  'Almendra': {'Flavor': 8.93, 'Texture': 6.57, 'Novelty': 9.43},
  'Avellana': {'Flavor': 4.25, 'Texture': 7.37, 'Novelty': 1.18},
  'Pistacho': {'Flavor': 6.36, 'Texture': 7.1, 'Novelty': 5.24},
  'Turrón': {'Flavor': 7.45, 'Texture': 8.68, 'Novelty': 2.08},
  'Piña': {'Flavor': 3.08, 'Texture': 0.59, 'Novelty': 4.64},
  'Melocotón': {'Flavor': 5.06, 'Texture': 2.26, 'Novelty': 7.58},
  'Té verde': {'Flavor': 2.04, 'Texture': 7.12, 'Novelty': 7.5},
  'Té chai': {'Flavor': 2.07, 'Texture': 7.58, 'Novelty': 0.75},
  'Canela': {'Flavor': 1.4, 'Texture': 3.13, 'Novelty': 3.45},
  'Jengibre': {'Flavor': 0.94, 'Texture': 2.34, 'Novelty': 7.31},
  'Dulce de leche': {'Flavor': 4.33, 'Texture': 5.6, 'Novelty': 3.41},
  'Manzana verde': {'Flavor': 9.09, 'Texture': 3.29, 'Novelty': 7.63},
  'Kiwi': {'Flavor': 8.38, 'Texture': 0.42, 'Novelty': 1.39},
  'Granada': {'Flavor': 4.8, 'Texture': 6.81, 'Novelty': 8.94},
  'Arándano': {'Flavor': 1.42, 'Texture': 3.17, 'Novelty': 6.51},
  'Melón': {'Flavor': 8.35, 'Texture': 7.48, 'Novelty': 3.04},
  'Sandía': {'Flavor': 5.19, 'Texture': 9.49, 'Novelty': 9.56},
  'Guayaba': {'Flavor': 4.51, 'Texture': 6.52, 'Novelty': 2.38},
  'Maracuyá': {'Flavor': 5.15, 'Texture': 7.72, 'Novelty': 1.71},
  'Papaya': {'Flavor': 1.81, 'Texture': 2.56, 'Novelty': 7.77},
  'Cereza': {'Flavor': 8.29, 'Texture': 7.97, 'Novelty': 2.71},
  'Uva': {'Flavor': 5.95, 'Texture': 2.85, 'Novelty': 4.36},
  'Higo': {'Flavor': 6.0, 'Texture': 0.22, 'Novelty': 6.28},
  'Ciruela': {'Flavor': 5.14, 'Texture': 6.43, 'Novelty': 7.4},
  'Mamey': {'Flavor': 6.66, 'Texture': 0.14, 'Novelty': 9.19},
  'Piñón': {'Flavor': 4.35, 'Texture': 9.98, 'Novelty': 5.9},
  'Chocolate blanco': {'Flavor': 5.19, 'Texture': 6.31, 'Novelty': 8.09},
  'Nutella': {'Flavor': 0.45, 'Texture': 0.98, 'Novelty': 8.38},
  'Orejón': {'Flavor': 2.17, 'Texture': 8.86, 'Novelty': 2.75},
  'Tutti Frutti': {'Flavor': 4.26, 'Texture': 8.56, 'Novelty': 2.18},
  'Chicle': {'Flavor': 2.89, 'Texture': 2.37, 'Novelty': 9.55},
  'Toronja': {'Flavor': 0.01, 'Texture': 1.19, 'Novelty': 9.37},
  'Mandarina': {'Flavor': 7.23, 'Texture': 5.39, 'Novelty': 8.96},
  'Tamarindo': {'Flavor': 3.26, 'Texture': 1.64, 'Novelty': 8.75},
  'Pera': {'Flavor': 7.05, 'Texture': 4.37, 'Novelty': 3.64},
  'Durazno': {'Flavor': 1.27, 'Texture': 0.97, 'Novelty': 0.25},
  'Guanábana': {'Flavor': 3.6, 'Texture': 2.33, 'Novelty': 5.02},
  'Pitahaya': {'Flavor': 9.22, 'Texture': 2.05, 'Novelty': 2.88},
  'Frutos rojos': {'Flavor': 4.62, 'Texture': 4.6, 'Novelty': 4.12},
  'Zanahoria': {'Flavor': 0.57, 'Texture': 4.84, 'Novelty': 8.9},
  'Dulce de membrillo': {'Flavor': 8.66, 'Texture': 9.58, 'Novelty': 7.28},
  'Crema catalana': {'Flavor': 4.24, 'Texture': 6.78, 'Novelty': 6.94},
  'Yogur': {'Flavor': 4.21, 'Texture': 6.36, 'Novelty': 6.81},
  'Arroz con leche': {'Flavor': 3.73, 'Texture': 5.04, 'Novelty': 4.43},
  'Queso': {'Flavor': 0.11, 'Texture': 3.09, 'Novelty': 0.93},
  'Crema de whisky': {'Flavor': 9.26, 'Texture': 5.77, 'Novelty': 4.9},
  'Huevo': {'Flavor': 2.65, 'Texture': 2.98, 'Novelty': 8.66},
  'Pudín de chocolate': {'Flavor': 8.82, 'Texture': 3.47, 'Novelty': 1.63},
  'Malvavisco': {'Flavor': 8.81, 'Texture': 6.26, 'Novelty': 1.04},
  'Jalea de frutas': {'Flavor': 2.27, 'Texture': 8.78, 'Novelty': 6.05},
  'Tarta de queso': {'Flavor': 1.14, 'Texture': 7.59, 'Novelty': 5.43},
  'Pastel de zanahoria': {'Flavor': 5.18, 'Texture': 8.85, 'Novelty': 3.57},
  'Brownie': {'Flavor': 2.14, 'Texture': 4.66, 'Novelty': 3.74},
  'Galleta': {'Flavor': 8.93, 'Texture': 3.83, 'Novelty': 1.16},
  'Gofre': {'Flavor': 3.63, 'Texture': 6.47, 'Novelty': 9.84},
  'Tiramisú': {'Flavor': 5.19, 'Texture': 5.18, 'Novelty': 3.05},
  'Pastel de tres leches': {'Flavor': 4.23, 'Texture': 8.03, 'Novelty': 9.98},
  'Flan': {'Flavor': 5.1, 'Texture': 9.53, 'Novelty': 0.36},
  'Crema de cacahuate': {'Flavor': 0.21, 'Texture': 4.35, 'Novelty': 3.76},
  'Maní': {'Flavor': 2.94, 'Texture': 3.92, 'Novelty': 6.52},
  'Macadamia': {'Flavor': 5.51, 'Texture': 1.78, 'Novelty': 0.48},
  'Cajeta': {'Flavor': 7.89, 'Texture': 5.95, 'Novelty': 5.08},
  'Maíz': {'Flavor': 3.77, 'Texture': 1.53, 'Novelty': 2.54},
  'Ciruela pasa': {'Flavor': 2.38, 'Texture': 0.18, 'Novelty': 3.67},
  'Datil': {'Flavor': 7.31, 'Texture': 9.75, 'Novelty': 4.41},
  'Uva pasa': {'Flavor': 5.28, 'Texture': 8.85, 'Novelty': 2.5},
  'Miel': {'Flavor': 1.45, 'Texture': 0.39, 'Novelty': 0.71},
  'Frutas tropicales': {'Flavor': 1.55, 'Texture': 7.96, 'Novelty': 3.11},
  'Guava': {'Flavor': 4.57, 'Texture': 5.47, 'Novelty': 8.63},
  'Zapote': {'Flavor': 9.24, 'Texture': 1.37, 'Novelty': 8.21},
  'Toronja rosa': {'Flavor': 5.69, 'Texture': 6.64, 'Novelty': 5.73},
  'Mandarina verde': {'Flavor': 9.1, 'Texture': 7.41, 'Novelty': 7.31},
  'Nuez': {'Flavor': 6.82, 'Texture': 2.62, 'Novelty': 9.2},
  'Amaranto': {'Flavor': 8.09, 'Texture': 4.25, 'Novelty': 0.9},
  'Pitahaya roja': {'Flavor': 2.0, 'Texture': 6.62, 'Novelty': 8.0},
  'Zapote negro': {'Flavor': 4.35, 'Texture': 0.76, 'Novelty': 4.96},
  'Nanche': {'Flavor': 4.04, 'Texture': 0.76, 'Novelty': 9.53},
  'Tuna': {'Flavor': 6.81, 'Texture': 5.73, 'Novelty': 3.48},
  'Lichi': {'Flavor': 5.91, 'Texture': 9.33, 'Novelty': 3.21},
  'Chabacano': {'Flavor': 6.03, 'Texture': 5.08, 'Novelty': 0.87},
  'Cacao': {'Flavor': 6.05, 'Texture': 6.23, 'Novelty': 8.28},
  'Jícama': {'Flavor': 7.38, 'Texture': 2.26, 'Novelty': 5.44},
  'Pepino': {'Flavor': 1.95, 'Texture': 0.64, 'Novelty': 8.0},
  'Mamey sapote': {'Flavor': 4.13, 'Texture': 2.7, 'Novelty': 7.29},
  'Anona': {'Flavor': 9.07, 'Texture': 1.58, 'Novelty': 6.83},
  'Ataulfo': {'Flavor': 3.77, 'Texture': 4.1, 'Novelty': 1.36},
  'Granada china': {'Flavor': 1.15, 'Texture': 6.44, 'Novelty': 1.92},
  'Guanábana criolla': {'Flavor': 8.8, 'Texture': 7.57, 'Novelty': 4.48},
  'Guayaba agria': {'Flavor': 0.49, 'Texture': 6.82, 'Novelty': 3.04},
  'Guayaba criolla': {'Flavor': 2.97, 'Texture': 6.08, 'Novelty': 2.08},
  'Naranja agria': {'Flavor': 2.05, 'Texture': 9.7, 'Novelty': 1.72},
  'Papaya maradol': {'Flavor': 8.76, 'Texture': 3.52, 'Novelty': 6.9},
  'Ciruela china': {'Flavor': 1.27, 'Texture': 3.39, 'Novelty': 1.72},
  'Ciruela dátil': {'Flavor': 4.55, 'Texture': 6.39, 'Novelty': 9.56},
  'Pera de agua': {'Flavor': 3.62, 'Texture': 0.71, 'Novelty': 5.85},
  'Pera manzana': {'Flavor': 3.68, 'Texture': 1.36, 'Novelty': 2.86},
  'Pera perón': {'Flavor': 5.16, 'Texture': 1.48, 'Novelty': 0.53},
  'Pera lechera': {'Flavor': 5.55, 'Texture': 0.16, 'Novelty': 6.68},
  'Pera oriental': {'Flavor': 0.38, 'Texture': 8.37, 'Novelty': 7.48},
  'Pera de verano': {'Flavor': 5.72, 'Texture': 6.83, 'Novelty': 2.34},
  'Tuna blanca': {'Flavor': 3.97, 'Texture': 9.17, 'Novelty': 0.94},
  'Tuna cardona': {'Flavor': 2.63, 'Texture': 0.03, 'Novelty': 4.96},
  'Tuna de Castilla': {'Flavor': 5.31, 'Texture': 0.74, 'Novelty': 9.31},
  'Tuna real': {'Flavor': 1.18, 'Texture': 7.55, 'Novelty': 4.86},
  'Tuna trebolera': {'Flavor': 3.6, 'Texture': 5.54, 'Novelty': 6.15},
  'Uva misionera': {'Flavor': 2.18, 'Texture': 6.73, 'Novelty': 7.96},
  'Uva pelea': {'Flavor': 9.24, 'Texture': 1.19, 'Novelty': 2.03},
  'Uva vinífera': {'Flavor': 7.4, 'Texture': 6.08, 'Novelty': 7.25},
  'Uva zalema': {'Flavor': 3.03, 'Texture': 7.61, 'Novelty': 3.32},
  'Uva zalema negra': {'Flavor': 8.65, 'Texture': 0.07, 'Novelty': 1.04},
  'Uva zalema rosada': {'Flavor': 3.53, 'Texture': 4.47, 'Novelty': 6.79},
  'Uva zalema roja': {'Flavor': 8.77, 'Texture': 4.85, 'Novelty': 0.25},
  'Uva zalema rosa': {'Flavor': 7.45, 'Texture': 8.53, 'Novelty': 5.77},
  'Naranja agria dulce': {'Flavor': 2.85, 'Texture': 1.28, 'Novelty': 0.5},
  'Naranja china': {'Flavor': 1.03, 'Texture': 8.33, 'Novelty': 9.19},
  'Naranja dulce': {'Flavor': 6.47, 'Texture': 4.62, 'Novelty': 1.21},
  'Naranja toronja': {'Flavor': 9.73, 'Texture': 5.0, 'Novelty': 8.12},
  'Naranja vinal': {'Flavor': 0.36, 'Texture': 5.26, 'Novelty': 7.5},
  'Naranja x': {'Flavor': 8.45, 'Texture': 9.98, 'Novelty': 7.39},
  'Tuna roja': {'Flavor': 1.49, 'Texture': 9.86, 'Novelty': 4.39},
  'Tuna negra': {'Flavor': 9.77, 'Texture': 3.48, 'Novelty': 1.94},
  'Tuna amarilla': {'Flavor': 6.44, 'Texture': 1.48, 'Novelty': 3.88},
  'Tuna verde': {'Flavor': 4.42, 'Texture': 9.4, 'Novelty': 0.1},
  'Tuna morada': {'Flavor': 2.72, 'Texture': 7.38, 'Novelty': 5.6},
  'Tuna anaranjada': {'Flavor': 4.11, 'Texture': 7.12, 'Novelty': 0.88},
  'Tuna azul': {'Flavor': 3.69, 'Texture': 1.23, 'Novelty': 3.04},
  'Tuna violeta': {'Flavor': 8.5, 'Texture': 7.65, 'Novelty': 4.79},
  'Tuna rosa': {'Flavor': 5.4, 'Texture': 0.31, 'Novelty': 7.37},
  'Tuna transparente': {'Flavor': 0.56, 'Texture': 9.92, 'Novelty': 1.82},
  'Tuna opaca': {'Flavor': 1.41, 'Texture': 8.22, 'Novelty': 8.5},
  'Tuna traslúcida': {'Flavor': 5.43, 'Texture': 5.29, 'Novelty': 3.72},
  'Naranja roja': {'Flavor': 3.76, 'Texture': 0.36, 'Novelty': 5.26},
  'Naranja rosada': {'Flavor': 0.72, 'Texture': 0.22, 'Novelty': 5.14},
  'Naranja amarilla': {'Flavor': 0.09, 'Texture': 9.23, 'Novelty': 9.69}},
 'ice_cream_bases': 
 {'Crema de leche': {'Flavor': 5.26,'Texture': 9.64,'Novelty': 4.6},
  'Leche': {'Flavor': 3.03, 'Texture': 3.44, 'Novelty': 5.77},
  'Yemas de huevo': {'Flavor': 1.22, 'Texture': 3.56, 'Novelty': 2.96},
  'Yogur': {'Flavor': 2.67, 'Texture': 5.8, 'Novelty': 0.85},
  'Fruta': {'Flavor': 7.61, 'Texture': 7.97, 'Novelty': 7.16},
  'Leche de coco': {'Flavor': 2.37, 'Texture': 7.22, 'Novelty': 0.62},
  'Leche de almendras': {'Flavor': 5.25, 'Texture': 9.31, 'Novelty': 8.85},
  'Leche de soja': {'Flavor': 5.51, 'Texture': 6.96, 'Novelty': 7.53},
  'Queso crema': {'Flavor': 7.7, 'Texture': 1.99, 'Novelty': 2.66},
  'Leche condensada': {'Flavor': 7.92, 'Texture': 3.45, 'Novelty': 0.83},
  'Ricotta': {'Flavor': 3.24, 'Texture': 1.47, 'Novelty': 8.66},
  'Plátanos congelados': {'Flavor': 7.88, 'Texture': 4.72, 'Novelty': 3.56}},
 'sweeteners': 
 {'Azúcar de caña': {'Flavor': 6.25,'Texture': 3.58,'Novelty': 1.11},
  'Jarabe de maíz': {'Flavor': 4.16, 'Texture': 9.31, 'Novelty': 8.45},
  'Miel': {'Flavor': 8.63, 'Texture': 3.24, 'Novelty': 9.73},
  'Stevia': {'Flavor': 4.87, 'Texture': 5.43, 'Novelty': 4.15},
  'Eritritol': {'Flavor': 3.72, 'Texture': 4.37, 'Novelty': 5.09},
  'Xilitol': {'Flavor': 0.29, 'Texture': 3.87, 'Novelty': 0.72},
  'Sucralosa': {'Flavor': 0.25, 'Texture': 1.4, 'Novelty': 7.6},
  'Aspartamo': {'Flavor': 8.33, 'Texture': 8.85, 'Novelty': 4.21},
  'Maltitol': {'Flavor': 9.6, 'Texture': 9.81, 'Novelty': 6.29},
  'Sorbitol': {'Flavor': 3.61, 'Texture': 8.48, 'Novelty': 3.54}},
 'toppings_syrups': 
 {'Chocolate fundido': {'Flavor': 8.43,'Texture': 2.49,'Novelty': 0.62},
  'Sirope de caramelo': {'Flavor': 0.37, 'Texture': 0.37, 'Novelty': 6.17},
  'Fresas frescas': {'Flavor': 8.37, 'Texture': 6.24, 'Novelty': 7.26},
  'Trozos de galleta': {'Flavor': 9.69, 'Texture': 2.39, 'Novelty': 6.66},
  'Maní triturado': {'Flavor': 0.33, 'Texture': 9.45, 'Novelty': 1.68},
  'Nata montada': {'Flavor': 5.93, 'Texture': 0.38, 'Novelty': 5.55},
  'Salsa de frambuesa': {'Flavor': 1.06, 'Texture': 3.14, 'Novelty': 8.34},
  'Trozos de brownie': {'Flavor': 5.03, 'Texture': 1.09, 'Novelty': 8.74},
  'Sirope de vainilla': {'Flavor': 8.03, 'Texture': 6.04, 'Novelty': 2.16},
  'Trozos de chocolate': {'Flavor': 0.53, 'Texture': 3.58, 'Novelty': 2.03},
  'Salsa de fresa': {'Flavor': 0.61, 'Texture': 1.65, 'Novelty': 6.17},
  'Coco rallado': {'Flavor': 0.45, 'Texture': 6.63, 'Novelty': 0.64},
  'Sirope de chocolate blanco': {'Flavor': 1.75,'Texture': 0.12,'Novelty': 2.06},
  'Trozos de frutas tropicales': {'Flavor': 5.97,'Texture': 2.68,'Novelty': 3.18},
  'Salsa de caramelo salado': {'Flavor': 1.97, 'Texture': 0.4, 'Novelty': 9.44},
  'Galletas trituradas': {'Flavor': 4.74, 'Texture': 5.15, 'Novelty': 2.26},
  'Sirope de menta': {'Flavor': 6.23, 'Texture': 1.51, 'Novelty': 4.39},
  'Trozos de oreo': {'Flavor': 8.32, 'Texture': 7.28, 'Novelty': 8.91},
  'Salsa de arándano': {'Flavor': 1.92, 'Texture': 0.39, 'Novelty': 8.72},
  'Almendras picadas': {'Flavor': 2.36, 'Texture': 6.73, 'Novelty': 4.29},
  'Sirope de avellana': {'Flavor': 5.12, 'Texture': 0.11, 'Novelty': 6.78},
  'Trozos de tarta de queso': {'Flavor': 1.15, 'Texture': 7.42, 'Novelty': 7.3},
  'Salsa de mango': {'Flavor': 8.22, 'Texture': 8.75, 'Novelty': 7.85},
  'Granola': {'Flavor': 8.88, 'Texture': 2.65, 'Novelty': 0.32},
  'Sirope de melocotón': {'Flavor': 9.65, 'Texture': 2.18, 'Novelty': 2.5},
  'Trozos de plátano': {'Flavor': 6.84, 'Texture': 5.1, 'Novelty': 6.56},
  'Salsa de mora': {'Flavor': 1.25, 'Texture': 3.63, 'Novelty': 4.68},
  'Pepitas de chocolate': {'Flavor': 9.78, 'Texture': 5.74, 'Novelty': 8.83},
  'Sirope de fresa silvestre': {'Flavor': 4.91,'Texture': 6.35,'Novelty': 9.92},
  'Trozos de galleta de mantequilla': {'Flavor': 8.8,'Texture': 5.03,'Novelty': 5.27}}
}
